agent:
  llm:
    type: anthropic
    model: claude-3-5-sonnet-20241022
  output_mode: native
environment:
  type: BrowsingEnvironment
  args:
    max_turns: 5
    available_files:
    - example_resources/2408.03314v1.pdf
    - example_resources/2023.inlg-genchal.17.pdf