agent:
  llm:
    type: anthropic
    model: claude-3-5-sonnet-20241022
  output_mode: custom-parser
  output_mode_kwargs:
    history:
      include_turn_number: true
      include_reasoning: false

environment:
  type: OfflineSearchEnvironment
  args:
    max_turns: 5